### ISSUE TITLE
Missing of include/config/auto.conf

### ISSUE THREAD

**Issue by kallianisawesome** [janvrany/riscv-debian#4]
Makefile:594: include/config/auto.conf: No such file or directory

/risk-linux/include/config/auto.conf is missing, is it necessary? 

Thanks!

**Comment by janvrany** [comment]
I don't know. Maybe if you can give me more details on what you did and a log I'll be able to tell more.

**Comment by kallianisawesome** [comment]
I figure it out, it's configuration of riscv based linux kernel. This file used to exits but now it's missing. It turns out that I can manually configure that. I appreciate your time and thank you for helping me.
