### ISSUE TITLE
getting error while doing ./debian-mk-rootfs.sh debian.img

### ISSUE THREAD

**Issue by billasurendra** [janvrany/riscv-debian#5]
Hi,

I am trying to boot riscv debian through qemu, I am following this link  https://github.com/janvrany/riscv-debian, but i am getting error on ./debian-mk-rootfs.sh debian.img step. Please can anyone help me out.

Error:
I: mounting debian.img into /tmp/tmp.JufrB1Ywb7
[sudo] password for surya: 
ls: cannot open directory '/tmp/tmp.JufrB1Ywb7/lost+found': Permission denied
I: riscv64 cannot be executed, falling back to qemu-user
I: running apt-get update...
done
Get:1 http://deb.debian.org/debian-ports sid InRelease [55.3 kB]
Get:2 http://deb.debian.org/debian-ports unreleased InRelease [56.6 kB]
Reading package lists...
E: Release file for http://deb.debian.org/debian-ports/dists/sid/InRelease is not valid yet (invalid for another 1h 2min 20s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian-ports/dists/unreleased/InRelease is not valid yet (invalid for another 1h 3min 10s). Updates for this repository will not be applied.
E: apt-get update -oAPT::Status-Fd=<$fd> -oDpkg::Use-Pty=false failed
I: umounting '/tmp/tmp.JufrB1Ywb7'

Thanks in advance
Billa

**Comment by janvrany** [comment]
@billasurendra : I tried just now and got different error: 
```
...
done
I: installing apt...
done
I: installing remaining packages inside the chroot...
done
I: cleaning package lists and apt cache...
done
done
Package: *
Pin: release a=experimental
Pin-Priority: 5
Get:1 http://cdn-fastly.deb.debian.org/debian-ports sid InRelease [55.3 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian-ports unreleased InRelease [56.6 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian-ports experimental InRelease [55.3 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian-ports sid/main riscv64 Packages [19.5 MB]
Get:5 http://cdn-fastly.deb.debian.org/debian-ports sid/main all Packages [8254 kB]                                                                                         
Get:6 http://cdn-fastly.deb.debian.org/debian-ports unreleased/main riscv64 Packages [123 kB]                                                                               
Get:7 http://cdn-fastly.deb.debian.org/debian-ports experimental/main all Packages [220 kB]                                                                                 
Get:8 http://cdn-fastly.deb.debian.org/debian-ports experimental/main riscv64 Packages [673 kB]                                                                             
Fetched 28.9 MB in 39s (740 kB/s)                                                                                                                                           
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nfs-common' instead of 'nfs-client'
Package libnettle6 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libhogweed4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libhogweed4' has no installation candidate
E: Package 'libnettle6' has no installation candidate
I: umounting '/tmp/tmp.Ywd9CfwGzy'
```

The problem is that Debian RISC-V repositories are shaky. The best is to wait few days and try again, waiting until it stabilizes. A month ago or so I build rootfs without any problem...

**Comment by janvrany** [comment]
Commit d07eb400 addresses your problem with invalid keys.
