### ISSUE TITLE
Errors downloading repository

### ISSUE THREAD

**Issue by Iripi97** [janvrany/riscv-debian#6]
Successfully able to get to the step where you type:
**git -C riscv-debian submodule update --init --recursive**
However encounter the following error:
**error: Server does not allow request for unadvertised object 00c0edab3459024dbb66ba39120a681c6a5b8100**
**Fetched in submodule path 'binutils-gdb', but it did not contain 00c0edab3459024dbb66ba39120a681c6a5b8100. Direct fetching of that commit failed.**

Is this an issue you are finding on your end, or know how to fix? (Running this on Debian 10)

**Comment by janvrany** [comment]
Yes, it was a bug. Should be fixed now in both 

 * linux-5.0 branch - bea461109554c160d58970906a328847ce58c846
 * linux-5.6 branch - 5baa434de7d5ceb31d584d0abb870625c0946eb9

It works for me now, so closing the issue. If it does not work for you, please comment and reopen. Thanks!
